name: CD - Antora base image

on:
  push:
    branches:
      - develop
    paths:
      - Databridge.Sage/**
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml

    - name: Build and Push Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGES_PAT: ${{ secrets.PACKAGES_PAT }}
      run: |
        export CI_REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        export PROJECT_NAME=$(echo "${CI_REPOSITORY_NAME}" | sed -e 's/^backend-//' -e 's/-/./g' -e 's/\b\(.\)/\u\1/g')
        echo "Transformed PROJECT_NAME is: ${PROJECT_NAME}"
        echo "Transformed CI_REPOSITORY_NAME is: ${CI_REPOSITORY_NAME}"
        
        docker login ghcr.io \
          --username automation@lungmuss.com \
          --password $GITHUB_TOKEN
        
        docker build . \
          --build-arg RELEASE_TAG=$PreReleaseTag \
          --build-arg SEMVER=${{ steps.gitversion.outputs.semVer }} \
          --build-arg INF_VER=${{ steps.gitversion.outputs.informationalVersion }} \
          --build-arg PROJECT_NAME=${PROJECT_NAME} \
          --build-arg GITHUB_TOKEN=${PACKAGES_PAT} \
          --build-arg GITHUB_USER=orion6dev \
          --build-arg BUILD_CONFIGURATION=Debug \
          --label org.opencontainers.image.source=https://github.com/lungmuss/${CI_REPOSITORY_NAME} \
          --tag ghcr.io/lungmuss/$CI_REPOSITORY_NAME:${{ steps.gitversion.outputs.semVer }} \
          --file Dockerfile
        
        docker tag ghcr.io/lungmuss/$CI_REPOSITORY_NAME:${{ steps.gitversion.outputs.semVer }} \
          ghcr.io/lungmuss/$CI_REPOSITORY_NAME:dev
        
        docker push ghcr.io/lungmuss/$CI_REPOSITORY_NAME:${{ steps.gitversion.outputs.semVer }}
        docker push ghcr.io/lungmuss/$CI_REPOSITORY_NAME:dev
