name: CD - Antora base image

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml

    - name: Build and Push Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login ghcr.io \
          --username automation@lungmuss.com \
          --password $GITHUB_TOKEN

        docker build . \
          --build-arg RELEASE_TAG=$PreReleaseTag \
          --label org.opencontainers.image.created=$(date --rfc-3339=seconds) \
          --label org.opencontainers.image.title="Antora Base Image" \
          --label org.opencontainers.image.description="Base Docker image for Antora" \
          --label org.opencontainers.image.url="https://github.com/lungmuss/${{ github.event.repository.name }}" \
          --label org.opencontainers.image.source="https://github.com/lungmuss/${{ github.event.repository.name }}" \
          --label org.opencontainers.image.version="${{ steps.gitversion.outputs.semVer }}" \
          --label org.opencontainers.image.revision="${{ github.sha }}" \
          --label org.opencontainers.image.vendor="Lungmuss" \
          --label org.opencontainers.image.licenses="MIT" \
          --label org.opencontainers.image.version.informational="${{ steps.gitversion.outputs.informationalVersion }}" \
          --tag ghcr.io/lungmuss/${{ github.event.repository.name }}:${{ steps.gitversion.outputs.semVer }} \
          --file Dockerfile

        docker tag ghcr.io/lungmuss/${{ github.event.repository.name }}:${{ steps.gitversion.outputs.semVer }} \
          ghcr.io/lungmuss/${{ github.event.repository.name }}:dev

        docker push ghcr.io/lungmuss/${{ github.event.repository.name }}:${{ steps.gitversion.outputs.semVer }}
        docker push ghcr.io/lungmuss/${{ github.event.repository.name }}:dev
